input.onButtonPressed(Button.A, function () {
    basic.pause(2000)
    Drones.Basic_action(Drones.Basicoptions.Takeoff)
    Drones.Hovering(1)
    basic.showArrow(ArrowNames.North)
    Drones.Move_action(Drones.Directionoptions.Forward, 60)
    basic.showArrow(ArrowNames.West)
    Drones.Move_action(Drones.Directionoptions.Left, 60)
    basic.showArrow(ArrowNames.South)
    Drones.Move_action(Drones.Directionoptions.Backward, 60)
    basic.showArrow(ArrowNames.East)
    Drones.Move_action(Drones.Directionoptions.Right, 60)
    basic.clearScreen()
    Drones.Hovering(1)
    Drones.Basic_action(Drones.Basicoptions.Landing)
})
Drones.initModule(Drones.Runmodes.Master)
basic.showIcon(IconNames.Yes)
